apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bootcamp
  name: bootcamp
  namespace: lab
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: bootcamp
  type: NodePort
status:
  loadBalancer: {}
